apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8xsrv
spec:
  selector:
    matchLabels:
      app: k8xsrv
  replicas: 2
  template:
    metadata:
      labels:
        app: k8xsrv
    spec:
      containers:
        - name: k8xcontainer
          image: malvfr/k8x:v1.0.1
          envFrom:
            - secretRef:
                name: k8xsrv-secret
          resources:
            requests:
              cpu: "0.1"
              memory: "200Mi"
            limits:
              memory: "350Mi"
              cpu: "0.3"
