apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: k8x-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: k8xsrv
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 25
